import Head from 'next/head'
import NavBar from '../components/NavBar/NavBar'
import Carrousel from '../components/Carrousel/Carrousel'
import Slider from '../components/Slider/Slider'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Club La Nacion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar></NavBar>
      <Carrousel></Carrousel>
      <Slider title="Turismo en Buenos Aires"
              subtitle=""
              button="TODOS LOS BENEFICIOS"
              isDesc={false}
              >
      </Slider>
      <Slider title="Codigos de descuento"
              subtitle="¿Sos socio de Club LA NACION? Descarga tu codigo y disfrutá beneficios exclusivos en tus marcas favoritas."
              button="TODOS LOS CODIGOS"
              isDesc={true}></Slider>
    </div>
  )
}
